// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

var count_tag = document.querySelector("#count");

var count = {
  contents: 0
};

function change_count(increment) {
  if (increment) {
    count.contents = count.contents + 1 | 0;
  } else {
    count.contents = count.contents - 1 | 0;
  }
  count_tag.innerHTML = count.contents === 0 ? "Count is zero" : "Count is " + String(count.contents);
  if (count.contents === 0) {
    count_tag.className = "count count-zero";
    return ;
  } else if (count.contents === -1) {
    count_tag.className = "count count-negative";
    return ;
  } else if (count.contents === 1) {
    count_tag.className = "count count-positive";
    return ;
  } else {
    return ;
  }
}

Belt_Array.forEach(document.querySelectorAll("button"), (function (button) {
        var match = button.id;
        switch (match) {
          case "minus-one" :
              return button.addEventListener("click", (function (param) {
                            return change_count(false);
                          }));
          case "plus-one" :
              return button.addEventListener("click", (function (param) {
                            return change_count(true);
                          }));
          default:
            console.log("err");
            return ;
        }
      }));

export {
  count_tag ,
  count ,
  change_count ,
  
}
/* count_tag Not a pure module */
